services:
  server:
    build:
      context: ./server-go
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      - redis
      - mongo
    volumes:
      - ./server-go/uploads:/app/uploads
    env_file:
      - ./server-go/.env
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: aip-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
  mongo:
    image: mongo:7
    container_name: aip-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
