name: aip_app
description: "AIT - AI Chat Application"
publish_to: 'none'
version: 1.0.31+32

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.3.0
  cached_network_image: ^3.4.0
  web_socket_channel: ^2.4.0
  connectivity_plus: ^6.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.0
  flutter_local_notifications: ^17.0.0
  open_file: ^3.3.0
  dio: ^5.4.0
  path_provider: ^2.1.0
  flutter_foreground_task: ^8.0.0
  provider: ^6.1.0
  image_picker: ^1.1.0
  video_player: ^2.9.0
  permission_handler: ^11.0.0
  webview_flutter: ^4.0.0
  flutter_markdown: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
